### ISSUE TITLE
$KEY= hoge fugaの時、echo $KEY すると、hoge fuga が出力される(bashはhoge)のみ

### ISSUE THREAD

**Issue by kaorishima** [naharagu/42_minishell#4]

**Comment by naharagu** [comment]
環境変数で$KEY= hoge fugaと設定されている場合、echo $KEYでhoge fuga が出力されるのがbashの挙動と理解しています。添付のようなケースと理解していますが（理解が間違っていたらすみません！）、hogeのみが出力されるケースはどのような場合でしょうか。
<img width="318" alt="Screen Shot 2023-03-25 at 8 11 58" src="https://user-images.githubusercontent.com/76852123/227702782-bffcc39c-1485-4074-80bf-a4a9809c9fb1.png">
